enum ActionsEnums {
    ERROR_SET_ERROR = 'error/SET_ERROR',
    ERROR_SET_WARNING = 'error/SET_WARNING',
    SET_SUCCESS = 'SET_SUCCESS',

    LOADING = 'Loading',
    SAVING = 'Saving',
    PROCESSING = 'Processing',

    GET_PRODUCTS = 'GET_PRODUCTS',
    GET_SHOP_DETAILS = 'GET_SHOP_DETAILS',
    GET_SHOPS = 'GET_SHOPS',

    GET_UNACCEPTED_SHOPS = ' GET_UNACCEPTED_SHOPS',

    GET_CITIES = 'GET_CITIES',
    GET_FLAVORS = 'GET_FLAVORS',
    GET_CATEGORIES = 'GET_CATEGORIES',

    GET_RATINGS = 'GET_RATINGS',

    GET_USER_PROFILE = 'GET_USER_PROFILE',
    GET_FAVOURITE_SHOPS = 'GET_FAVOURITE_SHOPS',
    GET_USER_RATINGS = 'GET_USER_RATINGS',
}

export default ActionsEnums;
