export enum RouterPathEnum {
    COMPANYSHOP = '/companyShop/:id',
    COMPANYACCOUNT = '/companyAccount',
    RESTAURANTREGISTRATION = '/restaurantRegistration',
    REGISTRATION = '/registration',
    LOGIN = '/login',
    PROFILE = '/profile',
    HOME = '/',
    Error404 = '',
    SHOP = '/shop/:id',
    ADMINPANEL = '/adminPanel',
    ACCEPTINGSHOPS = '/acceptingShops',
    FLAVORSLIST = '/flavorsList',
    CATEGORIESLIST = '/categoriesList',
}
